### ISSUE TITLE
"Failed doRefreshToken()"

### ISSUE THREAD

**Issue by I-am-a-node** [runnane/node-red-contrib-easee#19]
Hi,
I manage to catch the **"Failed doRefreshToken()"** this time. It is difficult as It doesn't seem to be picked up by the Catch node to be logged. It only appears in the Debug sidebar. 

Log: 
3 May 06:21:42 - [error] [easee-configuration:5fbb3dcbe3996daf] [easee] EaseeConfiguration::doRefreshToken() - Failed doRefreshToken(), exiting

I have created a test setup in a docker container to monitor the node function. No other setup, flow or application is running or connecting to the server using the same, the main account. There is only one tablet with the same login but hasn't been opened or been used during _this_ period when the error occurred (thinking if there was a login "clash"). All apps in handheld devices are logged in with separated user accounts. 

**The "Charger Streaming Client" fails to renew the Token.** 
runnane/node-red-contrib-easee is version 0.5.7

Main points

- No triggers or other REST requests are created in this node-red flow. Only monitoring.
- Error seem to be random as there is no other action (that I know of) from a flow that could have caused the issue.
- A few command response messages seem to be sent on the stream during the error.
- Error stops at manual triggered REST login.

Behaviour: 
- Day 1 around 11.20 the error appears in the Debug sidebar that links to the "easee-configuaration". I am not at the screen so haven't searched for any other message. This continues _ever hour_ up until the next day at 06.00 when three Command Respond messages are received.
- Day 2, Three id messages around 06:00 are received.

> ![Easee Screenshot 2024-05-03 Error 1](https://github.com/runnane/node-red-contrib-easee/assets/101867514/8f3673f1-e8f0-40d4-85b0-f11905285722)

          From  "[easee] EaseeConfiguration::doRefreshToken() - Failed doRefreshToken(), exiting"
          
To three command response messages id's: 22, 48 and 63

THEN... it goes back to the "[easee] EaseeConfiguration::doRefreshToken() - Failed doRefreshToken(), exiting" but shows the error for _every minute_ instead of ones an hour.

At 06:20 the three command response messages with id's 22, 48 and 63 returns.

I am at the screen and the error doesn't stop until I manually trigger a "login" with the REST Client. No more error messages.

************
I will continue to keep an eye on this. Hard to replicate but maybe find a workaround to improve.

Temp Workaround suggestion: IF this error appeared and got picked up by "the stream error output" on the stream node it would be possible to auto trigger a REST request LOGIN. This way the error would go away and get the stream node back running.

Thank you.

**Comment by I-am-a-node** [comment]
Adding notes on the log from the Stream Connected and disconnected output (same days as the above error).

Disconnected:
     {"time":"2024/05/02 08:52:28Z","level":"DEBUG","var":"msg","message":{"_connectionId":"wzK33fhjGw5cdK7ylaqh-g","payload":"Disconnected","_msgid":"b6dcd0799b0d9848"}}

Connected:
     {"time":"2024/05/02 08:52:39Z","level":"DEBUG","var":"msg","message":{"_connectionId":"zgmQSp6K1VxEVMybQ2QxcA","payload":"Connected","_msgid":"1726ec42da9dd7a9"}}
{"time":"2024/05/03 04:22:06Z","level":"DEBUG","var":"msg","message":{"_connectionId":"s5dXcXiPItpUbKzAiqD-kA","payload":"Connected","_msgid":"38a19e04cadd462d"}}
{"time":"2024/05/03 04:22:12Z","level":"DEBUG","var":"msg","message":{"_connectionId":"UmSS_DSbq6wePKg3i2cwog","payload":"Connected","_msgid":"aaa31b015838b9d8"}}

**Comment by KIDNORswe** [comment]
This looks similar to what I had. I can't figure out the reason behind it. Could be so many things.

Yea, One way to secure the node function and keeping the flow up running would be to catch this kind of error and have the option to trigger a flow to reset or run a re-login via the REST? 
It seem to be a connection between the STREAM and REST node as they use the same user and password config. And if the STREAM node keeps the token update working, the REST node can make its GET and POST actions.
I'll get back with any experience if this appears in my flow. 
But I like the idea to be able to fix a hick-up with a flow trigger.

**Comment by runnane** [comment]
I've released 0.5.8 with some more informative error messages, and automatic start/stop of refresh token timeouts. Please see how it works now.

**Comment by I-am-a-node** [comment]
Hi, @runnane good stuff, I'll get the new version up and running today and see how it goes.

**Comment by Deepfreeze10** [comment]
Hi Jon,

I still see the error in the node-red-contrib-easee (v0.6.2) with node-red (v3.1.5). Refresh_token function to api works fine though so no issues in using the node-red-contrib-easee module, only getting debug errors.

11 Dec 13:16:33 - [warn] [easee-configuration:ca77712e53942265] Error: Unable to refresh token, response not JSON: {"errorCode":104,"errorCodeName":"InvalidRefreshToken","type":null,"title":"Invalid refresh token","status":401,"detail":"[Empty in production]","instance":null,"extensions":{}}
Error: Unable to refresh token, response not JSON: {"errorCode":104,"errorCodeName":"InvalidRefreshToken","type":null,"title":"Invalid refresh token","status":401,"detail":"[Empty in production]","instance":null,"extensions":{}}
at /data/home/nodered/.node-red/node_modules/@runnane/node-red-contrib-easee/easee-client/easee-configuration.js:1258:21
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at EaseeConfiguration.node.doRefreshToken (/data/home/nodered/.node-red/node_modules/@runnane/node-red-contrib-easee/easee-client/easee-configuration.js:1238:26)

**Comment by KIDNORswe** [comment]
So frustrating that this error is still an issue. Appears for long minutes, repeating several times a day. And there is now workaround...  Can't tell if the "automatic start/stop of refresh token timeouts."

`"{"name":"Error","message":"Unable to refresh token, response not JSON: {\"errorCode\":104,\"errorCodeName\":\"InvalidRefreshToken\",\"type\":null,\"title\":\"Invalid refresh token\",\"status\":401,\"detail\":\"[Empty in production]\",\"instance\":null,\"extensions\":{}}"}"`

I'll forward the error message known as also posted from Deepfreeze in December. However I think I have to give up on this node now. I'll have to find another solutions cause this isn't working. Can't have such function that can't be trusted.

Thanks for all the work but I'm out.

**Comment by KIDNORswe** [comment]
Is this a clone from "/nordicopen/easee_hass"? They seem to have solved the connection issue. Can this be a guidance on how to solve this?

_"v0.9.64 - ...a newer version will help improve the stability of the Easee servers and free up resources for more quick response."_

**Comment by runnane** [comment]
Thanks for the update @KIDNORswe. I understand your frustation..
I have sadly been busy with family matters for the last year, and have has to down priotize my open source contributions. Feel free to add pull requests if you have suggestions and i will merge them! 
This project is not a fork, unfortunately.
For me both my nodered+easee instances work, but i guess this is an issue if you run commands a lot.

I will have a look at when I am able.

Jon

**Comment by KIDNORswe** [comment]
@runnane Jon, selvfølgelig! Family comes first. Keeping these open source functions alive is hard work as there are always changes and updates to keep up with.  Too heavy to maintain. Still annoyed with myself that I haven't learned more about coding so I can contribute. Still on my list .... 

No the issue appears randomly without any commands being sent. I read into another blog about another py script and they had the same issue. Looked like they found a solution.

Lets see if I manage to come up with any ideas on improvements and we can help each other. 
Cheers

**Comment by runnane** [comment]
@KIDNORswe Finally I was able to sit down and have a look. I've made the refresh and reauth processes more robust. A new release is up, so give it a try :)

**Comment by runnane** [comment]
Closing this as solved now, I have not had any issues for the last week (not counting the easee outage)
